### ISSUE TITLE
login has stopped working around 2018-04-05

### ISSUE THREAD

**Issue by pe-st** [moderation/garmin-connect-export#10]
On Thursday 2018-04-05 the login to Garmin Gonnect has stopped working (the day before it still worked):

(Stacktrace from my [develop branch](https://github.com/pe-st/garmin-connect-export/tree/develop)

    Traceback (most recent call last):
      File "./gcexport.py", line 201, in <module>
        hostname_url = http_req('http://connect.garmin.com/gauth/hostname')
    ...
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 503: Service Unavailable

**Comment by pe-st** [comment]
I have a fix working. I'm not sure about the URLs used, though. They work, but there might be better ones with less HTTP traffic...

**Comment by moderation** [comment]
Back from vacation and had time to finish my refactor into Python 3. A huge thanks to @pe-st for all of the testing and work he has done. This is now working for my cycling use case including CSV generation. I've not implemented some of the additional HTTP calls and functions that @pe-st did primarily for simplicity reasons.
