### ISSUE TITLE
Using activity-service-1.3 fails with HTTP Error 500

### ISSUE THREAD

**Issue by pe-st** [moderation/garmin-connect-export#11]
The current `gcexport3.py` has still the problem from pr #6.
- With `LIMIT_MAXIMUM = 1000` I get a HTTP error 400 from the activity-search-service-1.2 endpoint
- With `LIMIT_MAXIMUM = 100` I get a HTTP error 500 from the activity-search-service-1.2 endpoint
- When changing `LIMIT_MAXIMUM` to 18 or below I manage to retrieve about 7 activities, but then I get another 500, see this stacktrace:

    Activity details URL: https://connect.garmin.com/modern/proxy/activity-service-1.3/json/activityDetails/2620788460
    Traceback (most recent call last):
      File "gcexport3.py", line 388, in <module>
        ACTIVITY_DETAIL = http_req(URL_GC_ACTIVITY_DETAIL + str(a['activity']['activityId']))

**Comment by pe-st** [comment]
After the latest changes in gcexport3.py I don't get errors from activity-search-service-1.2 anymore, but the error 500 from activity-service-1.3 (ACTIVITY_DETAIL) still aborts the script (same stacktrace as in my initial report 17 days ago). Maybe my Garmin account has less privileges than yours?
If I paste the activity-service-1.3 URL into an open Connect session in the browser, I get the following JSON back:

    {"message":null,"error":"NullPointerException"}

**Comment by moderation** [comment]
@pe-st I'm not running into this error as I generally run the script after each activity or say get 3-5 activities at the end of the week. What is the use case to repeatedly download your entire history? Can you paste the JSON output from `activity-service-1.3` as maybe it is failing on JSON decode?

**Comment by pe-st** [comment]
@moderation I get the error already on the first activity (`python3 gcexport3.py --count 1 -f gpx`):

    ...
    login ticket=ST-22468181-4acRDRMObuTgKds3NURC-cas
    Request authentication URL: https://connect.garmin.com/modern/activities?ticket=ST-22468181-4acRDRMObuTgKds3NURC-cas
    Finished authentication
    Making activity request ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    https://connect.garmin.com/proxy/activity-search-service-1.2/json/activities?start=0&limit=1
    Finished activity request ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Activity list URL: https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=0&limit=1
    Garmin Connect activity: [2678784791] Butte-VsG-Givisiez-GP-Pérolles Longjog
      Sun, 6 May 2018 14:03, https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/2678784791?full=true
      Downloading file... Activity summary URL: https://connect.garmin.com/modern/proxy/activity-service/activity/2678784791
    Activity details URL: https://connect.garmin.com/modern/proxy/activity-service-1.3/json/activityDetails/2678784791
    Traceback (most recent call last):
      File "gcexport3.py", line 381, in <module>
        ACTIVITY_DETAIL = http_req(URL_GC_ACTIVITY_DETAIL + str(a['activity']['activityId']))
      File "gcexport3.py", line 101, in http_req
        response = OPENER.open((request), data=post)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 532, in open
        response = meth(req, response)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 642, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 570, in error
        return self._call_chain(*args)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 504, in _call_chain
        result = func(*args)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/urllib/request.py", line 650, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 500: Internal Server Error

**Comment by moderation** [comment]
@pe-st That is definitely strange. I don't normally specify `-f gpx` as that is the default and I thought that was the issue. But I just ran `./gcexport3.py --c 1 --username email@address.com --format gpx` and it worked fine. Python 3.6.3 on Xubuntu 17.10. What platform and Python version are you on?

**Comment by pe-st** [comment]
I'm on macOS and my python3 is 3.6.5 (see the stacktrace).

But as a HTTP Error 500 is a server-side error the different behaviour is probably linked to an issue at garmin (not the same software on all servers?) or a difference in our profiles.

**Comment by pe-st** [comment]
This activity-service-1.3 has spurious problems... I have run the script (well, gcexport.py in my fork, not gcexport3.py) twice for all my ~1000 activities and compared the result: 6 differences (failures to retrieve the measurements at all in one of both runs or a different number of measurements for the two runs. If you need reliable results here you might consider retrieving the measurements repeatedly until two consecutive results are equal ;-)

**Comment by moderation** [comment]
I can't reproduce the error and the latest version is working OK here. I
have a pretty limited usage however. I download in between 1 and 3 GPX
rides only. I don't have non-riding events and just download the delta
number of rides since my last download.

I'm on Ubuntu 18.04 and Python is 3.6.5. I just tested on MacOS which has
3.7 and again no errors. I use a Garmin Edge 520.

Not clear what is going on with your account that would generate server
side 500 errors.

**Comment by moderation** [comment]
Stale
