### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by whitas** [moderation/garmin-connect-export#14]
Hi again. Unfortunately I identified another issue in python3 version. Maybe it's connected with local characters? 

```
Garmin Connect activity: [2632311679] Aerobics, general - MyFitnessPal
	Śr, kwi 18, 2018 2:55 PM, 	Downloading file... Traceback (most recent call last):
  File "/Users/tomek/Garmin/garmin-connect-export//gcexport3.py", line 378, in <module>
    write_to_file(data_filename, data.decode(), file_mode)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 11: invalid start byte
```

**Comment by moderation** [comment]
Would it be possible to paste the content of the file that is trying to be written? Maybe add a `print(CONTENT)` to debug.

**Comment by whitas** [comment]
```
b"PK\x03\x04\x14\x00\x08\x08\x08\x00\xa2\x93\x93L\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0e\x00\x00\x002632311679.fit\xe3\x13\xe0\xe28\xcd\xc0\xc0\xa0\xe7\xe6\x19\x92\xd9\xe6\xc0\xc0\xc8\xc0\xc0\xca\xc2\xd2\xc6\xcc\xd2\xc3\xc8\xd4\xc2\xc4\xd4\x02\x120\xb5\xb2Z\x01T\xc2\xc8\xc0\xf8\xff\x1f\x0bH\x89!#\x03H\xc6\x01\xc4\x16g\xf9\xcb\xd2\x06T\xc8\x02\x12a\x82\xa8\x05\xaac\x00\xc9\t\xb3\x81\xe4X\xda\xd8Y\xda8X\xda8Y\xda\xb8\x81\x8aL\xadt'\x800Cto\x03\x08\xff\x07\x02\xc6- \xe5B\x1c\xc8\xca\xad\xc1\xcaY\x19\x19\xd8\xc0N@\xd5\x04\xc2\x8c[\x18\xc0\xb6(13\xb0\xb4\x01u\x02\x1d\xcc\x00\x12\x07\xabc|&\x0f\x00PK\x07\x08(\x00\t\xf6\x97\x00\x00\x00\xdb\x00\x00\x00PK\x01\x02\x14\x00\x14\x00\x08\x08\x08\x00\xa2\x93\x93L(\x00\t\xf6\x97\x00\x00\x00\xdb\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x002632311679.fitPK\x05\x06\x00\x00\x00\x00\x01\x00\x01\x00<\x00\x00\x00\xd3\x00\x00\x00\x00\x00"
```

That's it. 
It's manual entered activity (via MyFitnessPal). That's my its so short. But on my today long ride I have the same exception.

When I add **replace** to 
```
data.decode(errors='replace')
```

all wokrs OK, but I don't know what characters I'm loosing this way

**Comment by corbuno** [comment]
same problem on a non-manual activity

**Comment by corbuno** [comment]
It looks like gpx and tcx are saved to file without problem, only original (zip) is failing. And it seems to be on all activities as I have a new outdoor run today.

**Comment by kukukk** [comment]
Hi,

I can confirm that downloading in gpx and tcx formats are working, but downloading in original format is failing. I tried it on 2 cycling activities generated with a FR920XT and uploaded using the Garmin Connect mobile app.

Update1:
What is strange for me is that every time I execute the code it gets a different byte at the same position. If I understand correctly the code, the "data" variable in line 368 should be the content of the downloaded zip file. So it should have the same byte in that position, no?

Update2:
Using the following modification seems to work, but I can't explain why.
```
        if ARGS.format == 'original':
            content = data
        else:
            content = data.decode()
        write_to_file(data_filename, content, file_mode)
```

**Comment by pe-st** [comment]
I get the same error when trying to download format `original`. And I think that @kukukk 's modification might make sense. When a zip file is downloaded, no decode should happen as a zip file is binary and not utf-8 encoded.

**Comment by kukukk** [comment]
Unfortunately, I can't see any encoding related information in the response's header when downloading a track in different formats. Maybe checking the content-type field could help. When downloading directly from the Garmin Connect website these are the content-type values:
- content-type: application/x-zip-compressed
- content-type: application/gpx+xml
- content-type: application/vnd.garmin.tcx+xml

**Comment by kukukk** [comment]
Any update?
