### ISSUE TITLE
Not getting a ticket as of 4/16/19

### ISSUE THREAD

**Issue by hrpomrx** [moderation/garmin-connect-export#25]
`Exception: Did not get a ticket in the login response. Cannot log in. Did you enter the correct username and password?`

Password and userid work fine in browser.

**Comment by pe-st** [comment]
I have the same problem. Seems that Garmin changed the login process (again).
Couldn't get it to work yet, will need some more time.

**Comment by pe-st** [comment]
On my fork I could fix the issue, the most important changes are adding a referer and changing the URL from `.../sso/login` to `.../sso/signin`

**Comment by hrpomrx** [comment]
> On my fork I could fix the issue, the most important changes are adding a referer and changing the URL from `.../sso/login` to `.../sso/signin`

Thanks Peter! I was able to get it to work with your changes. I'll try your fork soon.

**Comment by moderation** [comment]
Fixed this in my repo with https://github.com/moderation/garmin-connect-export/commit/c381d39da7209bd4e7dd21f193513f5020148cb1. Massive thanks to @pe-st for the changes - they worked wonderfully.
