### ISSUE TITLE
WIN error - file in use and download not complete

### ISSUE THREAD

**Issue by rsjrny** [moderation/garmin-connect-export#26]
When executing multiple downloads I would run into WIN ERROR - File in use and also http  incomplete read errors

I added an 

import time
and in the list loop I added a time.sleep(3) delay. 

   for a in LIST:
        # Display which entry we're working on.
        **time.sleep(3)**
        print("Garmin Connect activity: [" + str(a["activityId"]) + "]", end=" ")

The delay cured all the error I ran into and have just completed a 150 file download without problem

**Comment by moderation** [comment]
Stale
