### ISSUE TITLE
Error downloading from Garmin

### ISSUE THREAD

**Issue by Haryt** [moderation/garmin-connect-export#29]
Hi, sice some days the download did not work anymore. I saw that the script from pe-st is fixed and working again, seems that Garmin changed someting during login.
Thanks for yore work!

Regards 
Hary

**Comment by wendlandreas** [comment]
[This fork](https://github.com/pe-st/garmin-connect-export) already contains a fix.

Regards,
Andreas

**Comment by moderation** [comment]
@Haryt I'll make the required hopefully tomorrow or early next week

**Comment by Haryt** [comment]
Thanks, no hurry in between I use the pe-st fork
Thanks for you’re wonderful work, it makes live much easyer!

Mit freundlichen Grüßen

Harald Tuma

Event-Log
Technische Dienstleistungen für Veranstaltungen und IT
Harald Tuma
Obermüllnerstrasse 11/55
1020 Wien
Austria
Mail: h.tuma@event-log.com<mailto:h.tuma@event-log.com>
Web: www.event-log.com<http://www.event-log.com/>
Tel: +43 (0)664 103 14 50
Bankverbindung: Sparkasse Horn-Ravelsbach
IBAN: AT872022107200000946 BIC: SPHNAT21
ATU: ATU59889669
EORI-Nummer ATEOS1000062771
AGB unter  http://www.event-log.com/uploads/div/AGB.pdf  abrufbar

Von: moderation <notifications@github.com>
Gesendet: Sonntag, 28. Februar 2021 01:01
An: moderation/garmin-connect-export <garmin-connect-export@noreply.github.com>
Cc: Harald Tuma - Event-Log <office@event-log.com>; Mention <mention@noreply.github.com>
Betreff: Re: [moderation/garmin-connect-export] Error downloading from Garmin (#29)


@Haryt<https://github.com/Haryt> I'll make the required hopefully tomorrow or early next week

**Comment by moderation** [comment]
I've added the fix and tested with my latest ride. Thanks to @pe-st and the rest of the community for the quick fix.

**Comment by Haryt** [comment]
Thanks!

What I also saw was, that if you use a Fēnix (have had a Fenix 5 for some days, normally I use Forerunner 945 or Edge 1030) device there are some problems with cp1252 in Python, because of the ē. If you download more then 1 activity it fails after every activity and you have to restart the script. The only fix I was able to find was to rename the utf_8.py to cp1252.py in the %PythonDirectory%\Lib\encodings. This is because I’m not a programmer, so I’m not able to see if there is any solution in the code. I saw that there is the instruction to python to use utf8, but it seems not to work, I testet it on 2 different PC’s, so I think it is not a setting on 1 PC.

Regards
Hary

Mit freundlichen Grüßen

Harald Tuma

Event-Log
Technische Dienstleistungen für Veranstaltungen und IT
Harald Tuma
Obermüllnerstrasse 11/55
1020 Wien
Austria
Mail: h.tuma@event-log.com<mailto:h.tuma@event-log.com>
Web: www.event-log.com<http://www.event-log.com/>
Tel: +43 (0)664 103 14 50
Bankverbindung: Sparkasse Horn-Ravelsbach
IBAN: AT872022107200000946 BIC: SPHNAT21
ATU: ATU59889669
EORI-Nummer ATEOS1000062771
AGB unter  http://www.event-log.com/uploads/div/AGB.pdf  abrufbar

Von: moderation <notifications@github.com>
Gesendet: Montag, 1. März 2021 01:29
An: moderation/garmin-connect-export <garmin-connect-export@noreply.github.com>
Cc: Harald Tuma - Event-Log <office@event-log.com>; Mention <mention@noreply.github.com>
Betreff: Re: [moderation/garmin-connect-export] Error downloading from Garmin (#29)


I've added the fix and tested with my latest ride. Thanks to @pe-st<https://github.com/pe-st> and the rest of the community for the quick fix.
