### ISSUE TITLE
The original activity is not necessarily a FIT file.

### ISSUE THREAD

**Issue by kukukk** [moderation/garmin-connect-export#3]
Hi,

I have some activities imported into my Garmin Connect account from GPX files (generated with Endomondo/MyTracks before I bought my Garmin device). In this case the original file is a GPX file and not FIT. It means that isfile(fit_filename) will never be true and the script will re-download the already existing file.
I can't see any information in the json response which would help identifying the original activity file, so it seems to be impossible to fix. I just wanted you to know this problem.

Best regards,
kukukk

**Comment by moderation** [comment]
Stale
