### ISSUE TITLE
Problem unzipping when no original file

### ISSUE THREAD

**Issue by adriangibbons** [moderation/garmin-connect-export#4]
Thanks for this script - yours was the only fork that worked for me, after I'd tried about 5! I was able to download all my activities but had to restart the script lots of times...

I was running it with the options ```--format original``` and ```--unzip``` and received the error message:
```
Garmin Connect activity: [12345678] Untitled swim
	Mon, 10 Jan 2011 6:30 PM, ??:??:??, 0.80 Kilometers
	Downloading file... Writing empty file since there was no original activity data... Unzipping and removing original files...
Traceback (most recent call last):
  File "gcexport-moderation.py", line 464, in <module>
    z = zipfile.ZipFile(zip_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

So the script fails when it tried to unzip the 0Kb zip file for activities where there is no original file. E.g. manually created activities, such as my swims!

Once the empty zip file is there though, the next time I ran the script it would keep going past this point.

Appreciated it's in the Description:

> If the original format is used, Garmin may not provide a file at all and an empty file will be created

But perhaps the script could be amended to not try and unzip 0Kb files? Or some other suitable approach to enable it to keep going. I don't know Python and have downloaded all my files with the manual workaround, but it would be beneficial for future users :+1:

**Comment by adriangibbons** [comment]
I think I ended up with massive JSON and CSV files as well as I had to re-run the script so many times. Perhaps the activities shouldn't be appended to these files if they already exist?

**Comment by moderation** [comment]
Thanks for report @adriangibbons. I think to fix the first issue we would need to add a check to the code at https://github.com/moderation/garmin-connect-export/blob/master/gcexport.py#L458-L464 to see if the file was > 0Kb before attempting to unzip. I'll do some testing over the weekend.

On the second issue I don't believe there is an option to batch downloads of large historical accounts. I think this would be a fair amount of work to add.

**Comment by moderation** [comment]
@adriangibbons can you test the latest commit https://github.com/moderation/garmin-connect-export/commit/51122586d4abf2537d9be592e2b9b5dcdfb701c9 to see if it works. I've done some basic testing on my side and it appears to work as intended. Let me know either way and I can either go back to the drawing board or close this issue.

**Comment by adriangibbons** [comment]
Hi @moderation 

Works like a charm - thanks for that. I just ran the script and it handled these manual activities without original files correctly:

```
Garmin Connect activity: [12334567] Swimming pool
	Tue, 25 Jan 2011 6:45 PM, ??:??:??, 1.00 Kilometers
	Downloading file... Writing empty file since there was no original activity data... Unzipping and removing original files... Filesize is: 0
Skipping 0Kb zip file.
Done.
```

**Comment by moderation** [comment]
Glad to hear it works @adriangibbons. Thanks for testing it.
