### ISSUE TITLE
problem since 2018-3-24

### ISSUE THREAD

**Issue by matmuc** [moderation/garmin-connect-export#9]
I'am getting this error since today:
Traceback (most recent call last):
  File "gcexport.py", line 318, in <module>
    print '\t' + a['activity']['activitySummary']['BeginTimestamp']['display'] + ',',
KeyError: 'activitySummary'

Thanks for your great Too!

**Comment by johannesh83** [comment]
Faced the same issues at my end. Therefore I refactored the script a bit and adjusted to my needs. Most probably this will also solve your issues as it then just downloads data from Garmin Connect and not longer feeds content to any csv files: [https://github.com/JohannesHeinrich/garmin-connect-export/](https://github.com/JohannesHeinrich/garmin-connect-export/)

**Comment by pe-st** [comment]
I can confirm that I as well don't get the `activitySummary` part of the JSON response anymore.

You might want to look at the pull request #7 (or my `develop` branch https://github.com/pe-st/garmin-connect-export/tree/develop), where I started to used another REST endpoint that still provides almost all the data needed to fill a CSV output (yes, the CSV is important for me...)

**Comment by joetimmerman** [comment]
@pe-st I have a [fork](https://github.com/joetimmerman/garmin-connect-export) that's similar to this one, but ported to Python 3 and with some minor changes/cleanup. I'm taking a look through your updates to see if they look feasible to integrate into my code. If it looks like it won't be a huge effort, do you mind if I use some of your code (and credit you for it)? I'm not concerned about maintaining the exact csv format.

**Comment by pe-st** [comment]
@joetimmerman Go for it, you're welcome!

**Comment by matmuc** [comment]
Since Yeaterday there is another Problem: 
https://connect.garmin.com/gauth/hostname: 503 not Available

Best Regards Matthias

**Comment by pe-st** [comment]
@matmuc Yes, this is noted in #10

**Comment by moderation** [comment]
@matmuc @joetimmerman @JohannesHeinrich @pe-st I've upgraded my fork to a `pylint3` linted Python 3 version also and made many changes primarily influenced by @pe-st fork. This script is now working for my use case.
